name: geduq_apps
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+6

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  audioplayers: ^6.4.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.3
  flutter_screenutil: ^5.9.3
  get_storage: ^2.1.1
  flutter_exit_app: ^1.1.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_apk.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/images/logo_apk.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/logo_apk.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo_apk.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/sounds/nama_surat_dari_ayat/
    - assets/sounds/sambung_ayat/
    - assets/sounds/susun_ayat/
    - assets/sounds/arti_ayat/
    - assets/sounds/materi_ayat/
    - assets/json/
